name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: mvn clean package -DskipTests

      - name: Create ZIP archive
        run: |
          mkdir -p artifact
          cp target/*.jar artifact/
          zip -r springboot-app.zip artifact/

      - name: Upload to AWS S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ secrets.BUCKET_NAME }}
          region: ${{ secrets.REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source-dir: .
          dest-dir: /

      - name: Cleanup
        run: rm -rf artifact springboot-app.zip
